bremersee:
  access:
    ip-addresses:
    - "127.0.0.1"
    - "::1"
    users:
    - name: actuator
      password: secret4ACTUATOR

eureka:
  client:
    enabled: false
    register-with-eureka: false

logging:
  level:
    ROOT: ${LOG_LEVEL_ROOT:INFO}
    org.springframework: ${LOG_LEVEL_SPRING:INFO}
    org.bremersee: ${LOG_LEVEL_BREMERSEE:DEBUG}

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: ${SERVER_PORT:8765}
  use-forward-headers: ${USE_FORWARD_HEADERS:true}
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
    port-header: x-forwarded-port

spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    default-property-inclusion: non_null
    property-naming-strategy: LOWER_CAMEL_CASE
    locale: de_DE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: GMT
  zipkin:
    enabled: false
    base-url: http://localhost:9411/

zuul:
  sensitive-headers:
  add-host-header: true
  add-proxy-headers: true
  strip-prefix: true
